window.GOLDEN_EMBER_PRODUCTS = {
  "truffle-mushroom-soup": {
    "name": "Truffle Mushroom Soup",
    "category": "Starters",
    "price": 14,
    "rating": 4.8,
    "reviews": 124,
    "image": "https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=1400&q=90",
    "desc": "Wild mushrooms blended with silky truffle cream, finished with toasted brioche and fresh herbs.",
    "details": "A refined, comforting starter with deep earthy flavour and a luxurious aromatic finish.",
    "prep": "15 minutes",
    "calories": "320 kcal"
  },
  "ember-prawns": {
    "name": "Ember Prawns",
    "category": "Starters",
    "price": 18,
    "rating": 4.9,
    "reviews": 168,
    "image": "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=1400&q=90",
    "desc": "Charred prawns tossed in garlic butter with citrus herbs and a touch of ember spice.",
    "details": "Juicy, flame-kissed prawns with bright citrus notes and a rich buttery glaze.",
    "prep": "18 minutes",
    "calories": "410 kcal"
  },
  "burrata-garden": {
    "name": "Burrata Garden",
    "category": "Starters",
    "price": 17,
    "rating": 4.7,
    "reviews": 96,
    "image": "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?auto=format&fit=crop&w=1400&q=90",
    "desc": "Creamy burrata with heirloom tomatoes, basil oil, sea salt and crisp garden leaves.",
    "details": "A fresh, elegant plate balancing creamy richness with bright seasonal produce.",
    "prep": "12 minutes",
    "calories": "360 kcal"
  },
  "crispy-calamari": {
    "name": "Crispy Calamari",
    "category": "Starters",
    "price": 16,
    "rating": 4.6,
    "reviews": 141,
    "image": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=1400&q=90",
    "desc": "Golden calamari served with lemon aioli, smoked paprika and fresh herbs.",
    "details": "Lightly crisp outside, tender inside, and perfect for sharing before the main course.",
    "prep": "16 minutes",
    "calories": "450 kcal"
  },
  "ember-ribeye": {
    "name": "Ember Ribeye",
    "category": "Mains",
    "price": 38,
    "rating": 4.9,
    "reviews": 287,
    "image": "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1400&q=90",
    "desc": "Prime ribeye with herb butter, roasted vegetables and our signature pepper jus.",
    "details": "Open-flame seared for a caramelized crust while remaining tender and juicy at the centre.",
    "prep": "30 minutes",
    "calories": "780 kcal"
  },
  "herb-chicken": {
    "name": "Herb Chicken",
    "category": "Mains",
    "price": 27,
    "rating": 4.7,
    "reviews": 173,
    "image": "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=1400&q=90",
    "desc": "Free-range chicken with mashed potato, seasonal vegetables and thyme jus.",
    "details": "Comforting, balanced and deeply savoury with a crisp herb-roasted finish.",
    "prep": "28 minutes",
    "calories": "650 kcal"
  },
  "lamb-chops": {
    "name": "Lamb Chops",
    "category": "Mains",
    "price": 36,
    "rating": 4.8,
    "reviews": 202,
    "image": "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1400&q=90",
    "desc": "Grilled lamb chops with rosemary glaze and roasted seasonal vegetables.",
    "details": "Tender chops with a fragrant herb crust and a rich, gently sweet glaze.",
    "prep": "32 minutes",
    "calories": "720 kcal"
  },
  "seafood-linguine": {
    "name": "Seafood Linguine",
    "category": "Mains",
    "price": 29,
    "rating": 4.7,
    "reviews": 184,
    "image": "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1400&q=90",
    "desc": "Fresh linguine with prawns, mussels, tomato, garlic and garden herbs.",
    "details": "A vibrant coastal pasta with fresh seafood and a light, aromatic tomato sauce.",
    "prep": "25 minutes",
    "calories": "690 kcal"
  },
  "golden-ember-burger": {
    "name": "Golden Ember Burger",
    "category": "Mains",
    "price": 22,
    "rating": 4.8,
    "reviews": 251,
    "image": "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1400&q=90",
    "desc": "Prime beef, cheddar, onion relish and ember sauce in a toasted brioche bun.",
    "details": "A bold house burger with a juicy patty, smoky sauce and sweet caramelized onion.",
    "prep": "20 minutes",
    "calories": "860 kcal"
  },
  "wild-mushroom-pasta": {
    "name": "Wild Mushroom Pasta",
    "category": "Mains",
    "price": 24,
    "rating": 4.6,
    "reviews": 138,
    "image": "https://images.unsplash.com/photo-1556761223-4c4282c73f77?auto=format&fit=crop&w=1400&q=90",
    "desc": "Fresh pasta with mushroom cream, parmesan and cracked black pepper.",
    "details": "Silky, earthy and satisfying, finished with aged parmesan and fresh herbs.",
    "prep": "22 minutes",
    "calories": "640 kcal"
  },
  "chocolate-lava-cake": {
    "name": "Chocolate Lava Cake",
    "category": "Desserts",
    "price": 13,
    "rating": 4.9,
    "reviews": 319,
    "image": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1400&q=90",
    "desc": "Warm chocolate cake with a molten centre, vanilla cream and cocoa crumble.",
    "details": "Rich dark chocolate with a soft flowing centre and a cool vanilla finish.",
    "prep": "14 minutes",
    "calories": "520 kcal"
  },
  "classic-tiramisu": {
    "name": "Classic Tiramisu",
    "category": "Desserts",
    "price": 12,
    "rating": 4.8,
    "reviews": 224,
    "image": "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1400&q=90",
    "desc": "Espresso-soaked layers with mascarpone cream and dark cocoa.",
    "details": "A classic Italian favourite with balanced coffee intensity and delicate sweetness.",
    "prep": "Ready to serve",
    "calories": "430 kcal"
  },
  "berry-cheesecake": {
    "name": "Berry Cheesecake",
    "category": "Desserts",
    "price": 12,
    "rating": 4.7,
    "reviews": 177,
    "image": "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=1400&q=90",
    "desc": "Vanilla cheesecake with berry compote and a crisp biscuit crumb.",
    "details": "Creamy and smooth with a bright berry finish and buttery base.",
    "prep": "Ready to serve",
    "calories": "470 kcal"
  },
  "ember-citrus": {
    "name": "Ember Citrus",
    "category": "Drinks",
    "price": 9,
    "rating": 4.6,
    "reviews": 92,
    "image": "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1400&q=90",
    "desc": "Orange, grapefruit, rosemary and sparkling water over ice.",
    "details": "Bright, refreshing and lightly herbal with a clean sparkling finish.",
    "prep": "5 minutes",
    "calories": "120 kcal"
  },
  "golden-passion": {
    "name": "Golden Passion",
    "category": "Drinks",
    "price": 10,
    "rating": 4.8,
    "reviews": 116,
    "image": "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=1400&q=90",
    "desc": "Passion fruit, lime, mint and tonic served chilled.",
    "details": "Tropical, tangy and aromatic with a refreshing botanical finish.",
    "prep": "5 minutes",
    "calories": "140 kcal"
  },
  "berry-nocturne": {
    "name": "Berry Nocturne",
    "category": "Drinks",
    "price": 9,
    "rating": 4.7,
    "reviews": 104,
    "image": "https://images.unsplash.com/photo-1546171753-97d7676e4602?auto=format&fit=crop&w=1400&q=90",
    "desc": "Mixed berries, basil and soda with crushed ice.",
    "details": "A vibrant alcohol-free blend with sweet berry flavour and fresh basil aroma.",
    "prep": "5 minutes",
    "calories": "130 kcal"
  },
  "grilled-beef-steak": {
    "name": "Grilled Beef Steak",
    "category": "Steak",
    "price": 32,
    "rating": 4.9,
    "reviews": 268,
    "image": "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=1400&q=90",
    "desc": "Charred tenderloin, herb butter, roasted vegetables and pepper jus.",
    "details": "A signature steak cooked over flame for deep flavour and a beautifully caramelized crust.",
    "prep": "28 minutes",
    "calories": "740 kcal"
  },
  "classic-beef-burger": {
    "name": "Classic Beef Burger",
    "category": "Burger",
    "price": 18,
    "rating": 4.8,
    "reviews": 244,
    "image": "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1400&q=90",
    "desc": "Prime beef, aged cheddar, caramelized onion and ember sauce.",
    "details": "Juicy, indulgent and layered with smoky-sweet flavours inside a toasted bun.",
    "prep": "18 minutes",
    "calories": "820 kcal"
  },
  "creamy-alfredo-pasta": {
    "name": "Creamy Alfredo Pasta",
    "category": "Pasta",
    "price": 21,
    "rating": 4.7,
    "reviews": 196,
    "image": "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1400&q=90",
    "desc": "Fresh fettuccine, parmesan cream, garlic and roasted mushrooms.",
    "details": "A rich, silky pasta with balanced garlic, parmesan and earthy mushroom notes.",
    "prep": "20 minutes",
    "calories": "710 kcal"
  }
};
